objects/Councillor_Details__c.object
<CustomObject>
    <fields>
        <fullName>Councillor_Email__c</fullName>
        <description>An email address for the Councillor.</description>
        <inlineHelpText>Please supply an email address for the Councillor.</inlineHelpText>
        <label>Councillor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Councillor_Image_URL__c</fullName>
        <description>A URL for an image of the Councillor.</description>
        <inlineHelpText>Please supply a URL for an image of the Councillor.</inlineHelpText>
        <label>Councillor Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Councillor_Info_URL__c</fullName>
        <description>A URL linking to more information about the Councillor (could be a web page or a PDF).</description>
        <inlineHelpText>Please supply a URL linking to more information about the Councillor (could be a web page or a PDF).</inlineHelpText>
        <label>Councillor Info URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Councillor_Phone__c</fullName>
        <description>A telephone number for the Councillor.</description>
        <inlineHelpText>Please supply a telephone number for the Councillor.</inlineHelpText>
        <label>Councillor Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Councillor_Type__c</fullName>
        <description>The type of Councillor ('Ward', 'District', 'County', 'MP' or 'MEP').</description>
        <inlineHelpText>Please supply the type of Councillor ('Ward', 'District', 'County', 'MP' or 'MEP').</inlineHelpText>
        <label>Councillor Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Political_Party__c</fullName>
        <description>The political party that the Councillor belongs to.</description>
        <inlineHelpText>Please supply the political party that the Councillor belongs to.</inlineHelpText>
        <label>Political Party</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ward_Code__c</fullName>
        <description>BS7666 Ward Code field. The ONS code of the electoral ward (ENG) or electoral division (CYM) name in which the BLPU is situated.</description>
        <inlineHelpText>The ONS code of the electoral ward (ENG) or electoral division (CYM) name in which the BLPU is situated.</inlineHelpText>
        <label>Ward Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>A custom setting to hold information about Councillors.</description>
    <label>Councillor Details</label>
</CustomObject>

classes/DSHLC_WidgetCouncillorCont.cls
/*
Company    :    Arcus Global
Product    :    Arcus DSH (Lightning DSH Core)
Purpose    :    Apex controller for Councillor Homepage Widget
Notes      :
*/
public with sharing class DSHLC_WidgetCouncillorCont extends DSHLC_ConfigSettings {

	@AuraEnabled
	public static Map<String, Object> getData(String recordId) {
		Map<String, Object> data = new Map<String, Object>();

		String wardCode = getContextWardCode(recordId);
		List<Councillor_Details__c> councillors = getCouncillorsDetails(wardCode);
		Map<String, String> wardCodeToLabelMap = getWardCodeToLabelMap();
		data.put('wardCode', wardCode);
		data.put('councillors', councillors);
		data.put('wardCodeToLabelMap', wardCodeToLabelMap);

		return data;
	}

	@TestVisible
	private static String getContextWardCode(String recordId) {
		String wardcode;

		if(String.isNotBlank(recordId)) {
			List<Contact> contacts = [SELECT Id, arcusgazetteer__Mailing_Address__r.arcusgazetteer__Ward_Name__c FROM Contact WHERE Id = :recordId AND arcusgazetteer__Mailing_Address__c != NULL LIMIT 1];
			if (!contacts.isEmpty()) {
				wardcode = contacts[0].arcusgazetteer__Mailing_Address__r.arcusgazetteer__Ward_Name__c;
			}
		} else {
			User loggedInUser = DSHLC_UserContact.getUserContact();

			if (loggedInUser.ContactId != null && loggedInUser.Contact.arcusgazetteer__Mailing_Address__c != null) {
				wardcode = [SELECT arcusgazetteer__Ward_Name__c FROM arcusgazetteer__Location__c WHERE Id = :loggedInUser.Contact.arcusgazetteer__Mailing_Address__c].arcusgazetteer__Ward_Name__c;
			}
		}

		return wardCode;
	}

	@TestVisible
	private static List<Councillor_Details__c> getCouncillorsDetails(String wardCode) {
		List<Councillor_Details__c> councillors = new List<Councillor_Details__c>();

		if (String.isNotBlank(wardcode)) {
			councillors = [
				SELECT 
					Name,
					Councillor_Email__c,
					Councillor_Image_URL__c,
					Councillor_Info_URL__c,
					Councillor_Phone__c,
					Councillor_Type__c,
					Political_Party__c,
					Ward_Code__c

				FROM Councillor_Details__c 
				WHERE Ward_Code__c = :wardcode
				OR Councillor_Type__c = 'County'
				OR Councillor_Type__c = 'District'
				OR Councillor_Type__c = 'MP'
				OR Councillor_Type__c = 'MEP'
				ORDER BY Name ASC NULLS LAST
			];
		}

		return councillors;
	}

	@TestVisible
	private static Map<String, String> getWardCodeToLabelMap() {
		Map<String, String> wardCodeToLabelMap = new Map<String, String>();
		for (Schema.PicklistEntry entry : arcusgazetteer__Location__c.arcusgazetteer__Ward_Name__c.getDescribe().getPicklistValues()) {
			wardCodeToLabelMap.put(entry.getValue(), entry.getLabel());
		}

		return wardCodeToLabelMap;
	}
}