objects/Council_Tax_Band__c.object
<CustomObject>
    <fields>
        <fullName>Council_Tax_Amount__c</fullName>
        <description>The overall amount for the Council Tax.</description>
        <inlineHelpText>Please supply the overall amount for the Council Tax.</inlineHelpText>
        <label>Council Tax Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Council_Tax_Band__c</fullName>
        <description>The Council Tax Band (i.e. A-H).</description>
        <inlineHelpText>Please supply the Council Tax Band (i.e. A-H).</inlineHelpText>
        <label>Council Tax Band</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Council_Tax_Year__c</fullName>
        <defaultValue>"20xx/20xx"</defaultValue>
        <description>The council tax year (aka period) - e.g. '2018/2019'.</description>
        <inlineHelpText>Please supply the council tax year (aka period) - e.g. '2018/2019'.</inlineHelpText>
        <label>Council Tax Year</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County_Council_Amount__c</fullName>
        <description>The amount for the County Council.</description>
        <inlineHelpText>Please supply the amount for the County Council.</inlineHelpText>
        <label>County Council Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>District_Council_Amount__c</fullName>
        <description>The amount for the District Council.</description>
        <inlineHelpText>Please supply the amount for the District Council.</inlineHelpText>
        <label>District Council Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fire_And_Rescue_Amount__c</fullName>
        <description>The Fire And Rescue Amount.</description>
        <inlineHelpText>Please supply the Fire And Rescue Amount.</inlineHelpText>
        <label>Fire And Rescue Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Police_And_Crime_Amount__c</fullName>
        <description>The Police And Crime Amount.</description>
        <inlineHelpText>Please supply the Police And Crime Amount.</inlineHelpText>
        <label>Police And Crime Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Social_Care_Amount__c</fullName>
        <description>The Social Care Amount.</description>
        <inlineHelpText>Please supply the Social Care Amount.</inlineHelpText>
        <label>Social Care Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_1_Amount__c</fullName>
        <description>The 1st Special Amount.</description>
        <inlineHelpText>Please supply the 1st Special Amount.</inlineHelpText>
        <label>Special 1 Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town_Council_Amount__c</fullName>
        <description>The amount for the Town Council.</description>
        <inlineHelpText>Please supply the amount for the Town Council.</inlineHelpText>
        <label>Town Council Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>A custom setting to hold information about Council Tax Bands.</description>
    <label>Council Tax Band</label>
</CustomObject>

classes/DSHLC_WidgetCouncilTaxCont.cls
/*
Company    :    Arcus Global
Product    :    Arcus DSH (Lightning DSH Core)
Purpose    :    Apex controller for Council Tax Homepage Widget
Notes      :           
*/
public with sharing class DSHLC_WidgetCouncilTaxCont extends DSHLC_ConfigSettings {
    
    @AuraEnabled
    public static List<Council_Tax_Band__c> getCouncilTaxBandDetails(String recordId) {
        List<Council_Tax_Band__c> bandDetails = new List<Council_Tax_Band__c>();

        String band;

        if(String.isNotBlank(recordId)) {       
            List<Contact> contacts = [SELECT arcusgazetteer__Mailing_Address__r.arcusgazetteer__BLPU__r.Council_Tax_Band__c FROM Contact WHERE Id = :recordId AND arcusgazetteer__Mailing_Address__c != NULL LIMIT 1];

            if (!contacts.isEmpty()) {
              band = contacts[0].arcusgazetteer__Mailing_Address__r.arcusgazetteer__BLPU__r.Council_Tax_Band__c;
            }
        } else {
            User loggedInUser = DSHLC_UserContact.getUserContact();
            
            if (loggedInUser.ContactId != null && loggedInUser.Contact.arcusgazetteer__Mailing_Address__c != null) {
              band = [
                SELECT arcusgazetteer__BLPU__r.Council_Tax_Band__c 
                FROM arcusgazetteer__Location__c 
                WHERE Id = :loggedInUser.Contact.arcusgazetteer__Mailing_Address__c
                ].arcusgazetteer__BLPU__r.Council_Tax_Band__c;
            }
        }

        if (String.isNotBlank(band)) {
            bandDetails = [
                SELECT 
                    Id, 
                    Name, 
                    Council_Tax_Band__c, 
                    Council_Tax_Year__c,
                    Council_Tax_Amount__c, 
                    County_Council_Amount__c, 
                    District_Council_Amount__c, 
                    Fire_And_Rescue_Amount__c, 
                    Police_And_Crime_Amount__c, 
                    Social_Care_Amount__c, 
                    Special_1_Amount__c, 
                    Town_Council_Amount__c 

                FROM Council_Tax_Band__c 
                WHERE Council_Tax_Band__c = :band

            ];

        }

        return bandDetails;
    }

}