objects/Council_Tax_Band__c.object
<CustomObject>
    <fields>
        <fullName>Council_Tax_Amount__c</fullName>
        <description>The overall amount for the Council Tax.</description>
        <inlineHelpText>Please supply the overall amount for the Council Tax.</inlineHelpText>
        <label>Council Tax Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Council_Tax_Band__c</fullName>
        <description>The Council Tax Band (i.e. A-H).</description>
        <inlineHelpText>Please supply the Council Tax Band (i.e. A-H).</inlineHelpText>
        <label>Council Tax Band</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Council_Tax_Year__c</fullName>
        <defaultValue>"20xx/20xx"</defaultValue>
        <description>The council tax year (aka period) - e.g. '2018/2019'.</description>
        <inlineHelpText>Please supply the council tax year (aka period) - e.g. '2018/2019'.</inlineHelpText>
        <label>Council Tax Year</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County_Council_Amount__c</fullName>
        <description>The amount for the County Council.</description>
        <inlineHelpText>Please supply the amount for the County Council.</inlineHelpText>
        <label>County Council Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>District_Council_Amount__c</fullName>
        <description>The amount for the District Council.</description>
        <inlineHelpText>Please supply the amount for the District Council.</inlineHelpText>
        <label>District Council Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fire_And_Rescue_Amount__c</fullName>
        <description>The Fire And Rescue Amount.</description>
        <inlineHelpText>Please supply the Fire And Rescue Amount.</inlineHelpText>
        <label>Fire And Rescue Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Police_And_Crime_Amount__c</fullName>
        <description>The Police And Crime Amount.</description>
        <inlineHelpText>Please supply the Police And Crime Amount.</inlineHelpText>
        <label>Police And Crime Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Social_Care_Amount__c</fullName>
        <description>The Social Care Amount.</description>
        <inlineHelpText>Please supply the Social Care Amount.</inlineHelpText>
        <label>Social Care Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Special_1_Amount__c</fullName>
        <description>The 1st Special Amount.</description>
        <inlineHelpText>Please supply the 1st Special Amount.</inlineHelpText>
        <label>Special 1 Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Town_Council_Amount__c</fullName>
        <description>The amount for the Town Council.</description>
        <inlineHelpText>Please supply the amount for the Town Council.</inlineHelpText>
        <label>Town Council Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>A custom setting to hold information about Council Tax Bands.</description>
    <label>Council Tax Band</label>
</CustomObject>

classes/DSHLC_WidgetCouncilTaxCont_Test.cls
/*
Company    :    Arcus Global
Product    :    Arcus DSH (Lightning DSH Core)
Purpose    :    Test class for Council Tax Homepage Widget
Notes      :           
*/
@isTest
private class DSHLC_WidgetCouncilTaxCont_Test {

  @isTest
	private static void testGetCouncilTaxBandDetailsWithRecordId() {

		List<Council_Tax_Band__c> testBandDetails = new List<Council_Tax_Band__c> {
			new Council_Tax_Band__c(
                Name = '2222/3333-Test A',
                Council_Tax_Band__c = 'A',
                Council_Tax_Year__c = '2222/3333',
                Council_Tax_Amount__c = 2000,
                County_Council_Amount__c  = 1567,
                District_Council_Amount__c  = 234,
                Fire_And_Rescue_Amount__c  = 123,
                Police_And_Crime_Amount__c = 678,
                Social_Care_Amount__c = 345, 
                Special_1_Amount__c = 20, 
                Town_Council_Amount__c = 100 
			)
		};
		insert testBandDetails;

		arcusgazetteer__BLPU__c blpu = new arcusgazetteer__BLPU__c(
			Council_Tax_Band__c = 'A'
		);
		insert blpu;

		arcusgazetteer__Location__c location = new arcusgazetteer__Location__c(
        	Name ='test street',
			arcusgazetteer__BLPU__c = blpu.Id
        );
        insert location;

        Contact testContact = new Contact(
        	LastName = 'test',
        	Email = 'test.user@DSHLCWidgetCouncilTaxCont.test.com',
        	arcusgazetteer__Mailing_Address__c = location.Id
        );
        insert testContact;


        Test.startTest();
        	List<Council_Tax_Band__c> result = DSHLC_WidgetCouncilTaxCont.getCouncilTaxBandDetails(testContact.Id);
        Test.stopTest();

        System.assertEquals('A', result[0].Council_Tax_Band__c, 'Wrong band, it should be A');
        System.assertEquals('2222/3333', result[0].Council_Tax_Year__c, 'Wrong year, it should be 2222/3333');
        System.assertEquals(2000, result[0].Council_Tax_Amount__c, 'Wrong amount for council tax, it should be 2000');
	}


	  @isTest
	private static void testGetCouncilTaxBandDetailsWithLoggedInUser() {

		List<Council_Tax_Band__c> testBandDetails = new List<Council_Tax_Band__c> {
			new Council_Tax_Band__c(
                Name = '2222/3333-Test D',
                Council_Tax_Band__c = 'D',
                Council_Tax_Year__c = '2222/3333',
                Council_Tax_Amount__c = 3000,
                County_Council_Amount__c  = 2567,
                District_Council_Amount__c  = 334,
                Fire_And_Rescue_Amount__c  = 223,
                Police_And_Crime_Amount__c = 778,
                Social_Care_Amount__c = 445, 
                Special_1_Amount__c = 30, 
                Town_Council_Amount__c = 200 
			)
		};
		insert testBandDetails;

		arcusgazetteer__BLPU__c blpu = new arcusgazetteer__BLPU__c(
			Council_Tax_Band__c = 'D'
		);
		insert blpu;

		arcusgazetteer__Location__c location = new arcusgazetteer__Location__c(
        	Name ='test2 street',
			arcusgazetteer__BLPU__c = blpu.Id
        );
        insert location;

        User loggedInUser = DSHLC_TestUtility.createCommunityUser();

        Contact loggedInUserContact = new Contact(
        	Id = loggedInUser.ContactId,
        	Email = 'test2.user@DSHLCWidgetBinCollectionCont.Test.com',
        	arcusgazetteer__Mailing_Address__c = location.Id
        );
        update loggedInUserContact;

        String testRecordId = null;

        System.runAs(loggedInUser) {
	        Test.startTest();
	        	List<Council_Tax_Band__c> result = DSHLC_WidgetCouncilTaxCont.getCouncilTaxBandDetails(testRecordId);
	        Test.stopTest();

	        System.assertEquals('D', result[0].Council_Tax_Band__c, 'Wrong band, it should be D');
	        System.assertEquals(223, result[0].Fire_And_Rescue_Amount__c, 'Wrong amount for fire and rescue, it should be 233');
		}
	}


}