objects/Street_Naming_Numbering_Application__c.object
<CustomObject>
    <fields>
        <fullName>Status_History__c</fullName>
        <description>Store the history of statuses.</description>
        <inlineHelpText>Store the history of statuses.</inlineHelpText>
        <label>Status History</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the SN&amp;N application.</description>
        <inlineHelpText>The status of the SN&amp;N application.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Application</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Application Approved</fullName>
                </value>
                <value>
                    <fullName>Application Refused</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Application for a change to a property name or for a new postal address.</description>
    <label>Street Naming &amp; Numbering Application</label>
    <nameField>
        <displayFormat>SNN-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Street Naming &amp; Numbering Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StreetNamingNumberingTriggerHandler.cls
global class StreetNamingNumberingTriggerHandler extends arcshared.TriggerDispatcher.TriggerHandler {
    global override void MainEntry(List<SObject> newlist, Map<ID, SObject> newmap, List<SObject> oldlist, Map<ID,SObject> oldmap){
        if(Trigger.isBefore && Trigger.isUpdate){            
            for(SObject snn : newlist){
                Street_Naming_Numbering_Application__c newSNN = (Street_Naming_Numbering_Application__c)snn;
                Street_Naming_Numbering_Application__c oldSNN = (Street_Naming_Numbering_Application__c)oldmap.get(newSNN.Id);
 
                if(newSNN.Status__c!= oldSNN.Status__c){
                    String history = String.isNotBlank(newSNN.Status_History__c) ? newSNN.Status_History__c: '';
                    if(String.isNotBlank(history)) history += ';';
                    newSNN.Status_History__c= history + oldSNN.Status__c;
                }
            }
        }
    }
}